-- 0001 — Extensions and domain enums
-- Spec: docs/mvp/05-database-schema.md §1

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TYPE meal_plan_t      AS ENUM ('ROOM_ONLY','BREAKFAST','HALF_BOARD','FULL_BOARD','ALL_INCLUSIVE','UNKNOWN');
CREATE TYPE refund_policy_t  AS ENUM ('REFUNDABLE','PARTIALLY_REFUNDABLE','NON_REFUNDABLE','UNKNOWN');
CREATE TYPE rate_audience_t  AS ENUM ('PUBLIC','MEMBER','CONSORTIA','NEGOTIATED','OPAQUE','UNKNOWN');
CREATE TYPE tax_basis_t      AS ENUM ('NET','GROSS','UNKNOWN');
CREATE TYPE room_class_t     AS ENUM ('ROOM','JUNIOR_SUITE','SUITE','VILLA','RESIDENCE','PENTHOUSE','UNKNOWN');
CREATE TYPE bed_config_t     AS ENUM ('KING','QUEEN','DOUBLE','TWIN','SINGLE','MULTIPLE','UNKNOWN');
CREATE TYPE view_t           AS ENUM ('OCEAN','PARTIAL_OCEAN','CITY','GARDEN','POOL','MOUNTAIN','INTERIOR','UNKNOWN');
CREATE TYPE match_method_t   AS ENUM ('SOURCE_ID','ALIAS_EXACT','ALIAS_FUZZY','ATTRIBUTE_INFERRED','UNMATCHED');
CREATE TYPE season_band_t    AS ENUM ('LOW','SHOULDER','HIGH','PEAK','UNKNOWN');
CREATE TYPE dow_bucket_t     AS ENUM ('WEEKDAY','WEEKEND');
CREATE TYPE recommendation_t AS ENUM ('BOOK_NOW','WAIT','CONSIDER','INSUFFICIENT_DATA');
CREATE TYPE score_band_t     AS ENUM ('EXCELLENT','GOOD','FAIR','BELOW_AVERAGE','POOR');
CREATE TYPE conf_band_t      AS ENUM ('HIGH','MODERATE','LOW','INSUFFICIENT');
CREATE TYPE benefit_basis_t  AS ENUM ('PER_NIGHT','PER_STAY');
